[audio]
enable_overdrive = true
enable_sounds = true

[bar]
order = [ "main" ]

    [bar.main]
    
    border_width = 0.29999999999999999
    capsule = true
    capsule_opacity = 0.5
    center = [ "group:g3" ]
    color = "primary"
    end = [ "tray", "clock-12h", "group:g1", "group:g4" ]
    font_weight = 700
    margin_edge = 0
    margin_ends = 0
    position = "top"
    radius = 0
    scale = 0.90000000596046448
    start = [ "Shin", "group:g2" ]
    thickness = 25

        [[bar.main.capsule_group]]
        fill = "surface_variant"
        id = "g3"
        members = [ "media", "lrc" ]
        opacity = 1.0
        padding = 6.0
        radius = 8.0

        [[bar.main.capsule_group]]
        fill = "surface_variant"
        id = "g2"
        members = [ "workspaces", "audio_visualizer", "bongocat" ]
        opacity = 1.0
        padding = 6.0
        radius = 8.0

        [[bar.main.capsule_group]]
        fill = "surface_variant"
        id = "g1"
        members = [ "ram", "cpu", "battery" ]
        opacity = 0.5
        padding = 6.0
        radius = 8.0

        [[bar.main.capsule_group]]
        fill = "surface_variant"
        id = "g4"
        members = [ "screen_recorder" ]
        opacity = 1.0
        padding = 6.0

[desktop_widgets]
schema_version = 1
widget_order = [ "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    cx = 976.0
    cy = 1080.0
    output = "eDP-2"
    rotation = 0.0
    scale = 5.1639776229858398
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        aspect_ratio = 6.0
        background = false
        bands = 96.0
        centered = true
        mirrored = true
        show_when_idle = false

[dock]
auto_hide = true

enabled = true
icon_size = 30
radius = 5

[hooks]
colors_changed = "plasma-apply-colorscheme noctalia"
session_locked = "~/.local/bin/kb-hook.bash"
theme_mode_changed = "plasma-apply-colorscheme noctalia"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

[keybinds]
down = [ "Ctrl+n", "Down" ]
up = [ "Ctrl+p", "Up" ]
validate = [ "Ctrl+y", "Return" ]

[location]
address = "Cairo, Egypt"
auto_locate = false
sunrise = "8:00"
sunset = "21:00"

[lockscreen]
blur_intensity = 0.89999997988343239
blurred_desktop = true
wallpaper = "/home/shin/Pictures/homework/norm/143296243-4a29a38c6585c30d999b3a1d719f2893_p28.png"

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = []

    [lockscreen_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget]

[nightlight]
enabled = true

[notification]
show_app_name = false

[notifications]


[osd]

orientation = "vertical"
position = "bottom_right"

[shell]
app_icon_colorize = true
avatar_path = "/home/shin/Pictures/homework/ecchi/random-poses/134115683_p34.webp"
clipboard_auto_paste = "off"
corner_radius_scale = 0.70000001043081284
font_family = "DejaVu Sans Mono"
launch_apps_as_systemd_services = true
password_style = "random"
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = true
telemetry_enabled = false
ui_scale = 0.90000000596046448

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"

    [shell.screen_corners]
    size = 1

    [shell.screenshot]
    directory = "/home/shin/Pictures/Screenshots"
    pipe_command = "swappy"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    label = "Suspend"
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "5"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.69999998435378075
    direction = "center"

[theme]
builtin = "Gruvbox"
community_palette = "Shien"
custom_palette = "Miasma"
mode = "light"
source = "custom"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "foot", "gtk3", "gtk4", "ghostty", "kcolorscheme", "kitty", "niri", "qt", "starship" ]
    community_ids = [ "spicetify", "zen-browser", "discord", "papirus-icons", "telegram", "yazi" ]
    enable_builtin_templates = true
    enable_community_templates = true

        [theme.templates.user.starship]
        input_path = "~/.config/matugen/templates/starship/starship-colors.toml"
        output_path = "~/.config/starship.toml"
        post_hook = "bash ~/.local/bin/theme-switch-hook.bash"

        [theme.templates.user.tmux]
        input_path = "~/.config/matugen/templates/tmux/tmux-colors.conf"
        output_path = "~/.config/tmux/theme.conf"
        post_hook = "~/.local/bin/tmux-hook.bash"

        [theme.templates.user.which-key]
        input_path = "~/.config/matugen/templates/which-key/colors.json"
        output_path = "~/.config/wlr-which-key/colors.json"
        post_hook = "~/.local/bin/which-key.sh"

[wallpaper]
directory = "/home/shin/Pictures"
enabled = true
fill_color = "#111111"
fill_mode = "stretch"
transition = [ "disc", "zoom" ]

    [wallpaper.automation]
    enabled = false
    interval_minutes = 30
    order = "random"
    recursive = false

    [wallpaper.default]
    path = "/home/shin/Pictures/homework/ecchi/leaning-boobi/138187398_p36.webp"

    [wallpaper.last]
    path = "/home/shin/Pictures/homework/ecchi/leaning-boobi/138187398_p36.webp"

    [wallpaper.monitors.eDP-2]
    path = "/home/shin/Pictures/homework/ecchi/leaning-boobi/138187398_p36.webp"

[widget.Shin]
anchor = true
capsule = true
font_weight = 700
glyph = ""
label = "死Shin  "
scale = 1.05
scroll_down_command = "noctalia msg volume-down"
scroll_up_command = "noctalia msg volume-up"
type = "custom_button"

[widget.audio_visualizer]
width = 100.0

[widget.battery]
capsule = true
capsule_radius = 0
hide_when_full = true
hide_when_plugged = true

[widget.bongocat]
audio_spectrum = true
input_device = "/dev/input/event8"
script = "scripts/bongocat.lua"
tappy_mode = true
type = "scripted"

[widget.clock]
format = """{:%H:%M}
{:%d/%m}"""
tooltip_format = "{:%A, %B %d, %Y}"
vertical_format = """{:%H
%M}"""

[widget.clock-12h]
capsule = true
format = "{:%-I:%M %p} - {:%d/%m}"
tooltip_format = "{:%A, %B %d, %Y}"
type = "clock"

[widget.clock-seconds]
format = "{:%H:%M:%S}"
type = "clock"

[widget.control-center]
capsule = true
capsule_padding = 14.0
glyph = "navigation-filled"
scale = 0.90000000000000013

[widget.cpu]
capsule = true
scale = 1.05
show_label = false

[widget.custom_button_2]
capsule = true
capsule_padding = 4.0
glyph = ""
label = "死Shin"
type = "custom_button"

[widget.custom_button_3]
glyph = ""
label = "|"
type = "custom_button"

[widget.lrc]
type = "shin/lrc:lrc"

[widget.media]
art_size = 20.0
capsule_radius = 0
max_length = 350
title_scroll = "on_hover"

[widget.pomodoro]
hot_reload = true
scope = "shared"
script = "~/.config/noctalia/scripts/pomodoro.lua"
type = "scripted"

[widget.ram]
scale = 1.05
show_label = false

[widget.screen_recorder]
color_range = "full"
directory = "/Media/Records/screencast/"
restore_portal = true
scale = 1.05
script = "scripts/screen_recorder.lua"
type = "scripted"
video_source = "portal"

[widget.scripted_2]
type = "scripted"

[widget.scripted_3]
type = "scripted"

[widget.tray]
capsule = true
drawer = true
hidden = [ "wayscriber", "blueman", "network" ]
match_adjacent_spacing = true

[widget.volume]
capsule = true
show_label = false

[widget.workspaces]
display = "name"
hide_when_empty = false
labels_only_when_occupied = true
max_label_chars = 2
pill_scale = 0.84999999999999998
