{ config, lib, ... }:
{
  imports = [
    ./baseline.nix
    ./packages.nix
    ./niri.nix
    ./nixvim
    ./yazi.nix
    ./polkit.nix
    ./virtualization.nix
    ./games
    ./network
    ./security
    ./services
    ./system
    ./memory
    ./media
    ./audio
    ./hardware/nvidia.nix
    ./hardware/touchpad.nix
    ./hardware/media/sound.nix
    ./tuning/tlp
    ./zen
    ./kde.nix
    ./hypr.nix
    ./xfce.nix
    ./gnome.nix
    ./home-options.nix
  ];
}
