{ config, pkgs, lib, osConfig, isServer ? false, ... }:

let
  inherit (builtins) readFile;
  inherit (lib) concatStringsSep mapAttrsToList mapAttrs filterAttrs optionalString optionals optional;

  cfg = config.programs.nix-tmux;

  # ── Plugin definitions ──────────────────────────────────────────

  pluginDefs = {
    tpm = {
      pkg = pkgs.tmuxPlugins.mkTmuxPlugin {
        pluginName = "tpm";
        version = "3.1.0";
        src = pkgs.fetchFromGitHub {
          owner = "tmux-plugins";
          repo = "tpm";
          rev = "v3.1.0";
          sha256 = "18i499hhxly1r2bnqp9wssh0p1v391cxf10aydxaa7mdmrd3vqh9";
        };
      };
      nixDir = "tpm";
      defaultRef = "tmux-plugins/tpm";
    };
    sensible = {
      pkg = pkgs.tmuxPlugins.sensible;
      nixDir = "sensible";
      defaultRef = "tmux-plugins/tmux-sensible";
    };
    yank = {
      pkg = pkgs.tmuxPlugins.yank;
      nixDir = "yank";
      defaultRef = "tmux-plugins/tmux-yank";
    };
    resurrect = {
      pkg = pkgs.tmuxPlugins.resurrect;
      nixDir = "resurrect";
      defaultRef = "tmux-plugins/tmux-resurrect";
    };
    thumbs = {
      pkg = pkgs.tmuxPlugins.tmux-thumbs;
      nixDir = "tmux-thumbs";
      defaultRef = "fcsonline/tmux-thumbs";
    };
    fzf = {
      pkg = pkgs.tmuxPlugins.tmux-fzf;
      nixDir = "tmux-fzf";
      defaultRef = "sainnhe/tmux-fzf";
    };
    fzf-url = {
      pkg = pkgs.tmuxPlugins.fzf-tmux-url;
      nixDir = "fzf-tmux-url";
      defaultRef = "wfxr/tmux-fzf-url";
    };
    sessionx = {
      pkg = pkgs.tmuxPlugins.tmux-sessionx;
      nixDir = "sessionx";
      defaultRef = "omerxx/tmux-sessionx";
    };
  };

  # Derive TPM directory name from plugin ref (part after /)
  tpmDirFromRef = ref: lib.elemAt (lib.splitString "/" ref) 1;

  # Store paths for activation symlinks
  pluginStorePaths = mapAttrs (name: def:
    "${def.pkg}/share/tmux-plugins/${def.nixDir}"
  ) pluginDefs;

  # Only enabled plugins
  enabledPlugins = filterAttrs (name: pcfg: pcfg.enable) cfg.plugins;

  # ── Config generation helpers ───────────────────────────────────

  mkPluginLine = name: "set -g @plugin '${cfg.plugins.${name}.tpmPluginRef}'";

  mkPluginSettings = name: pcfg:
    concatStringsSep "\n" (mapAttrsToList (key: value:
      "set -g @${key} '${value}'"
    ) (pcfg.settings or {}));

  mkFzfEnv = name: pcfg:
    concatStringsSep "\n" (mapAttrsToList (key: value:
      "${key}=\"${value}\""
    ) (pcfg.env or {}));

  # ── Sesh command ────────────────────────────────────────────────

  seshCmd = ''
    sesh connect \"\$(
      sesh list --icons | fzf-tmux -p 80%,70% \
        --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
        --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
        --bind 'tab:down,btab:up' \
        --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
        --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
        --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
        --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
        --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
        --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
        --preview-window 'right:55%' \
        --preview 'sesh preview {}'
    )\"'';

  # ── Build tmux.conf ─────────────────────────────────────────────

  tmuxConfLines = []
    ++ [ "# Generated by home-manager (nix-tmux). Edit at your own risk." ]
    ++ [ "" ]
    ++ [ "# ── Reset ──" ]
    ++ [ "source-file ~/.config/tmux/tmux.reset.conf" ]
    ++ [ "" ]
    ++ optionals (!isServer) [
      "# ── Session tracking ──"
      ''set-hook -g client-session-changed "run-shell 'current=\$(tmux display-message -p \"#S\"); case \"\$current\" in scratch-*) ;; *) mkdir -p ~/.local/state; echo \"\$current\" > ~/.local/state/tmux_last_session;; esac'"''
    ]
    ++ [ "" ]
    ++ [ "# ── Prefix ──" ]
    ++ [ "set-option -g prefix ${cfg.prefix}" ]
    ++ [ "bind ${cfg.prefix} send-prefix" ]
    ++ [ "" ]
    ++ optionals cfg.enableVimNavigator [
      "# ── Vim navigator ──"
      ''is_vim="${cfg.isVimCommand}"''
      ''bind -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"''
      ''bind -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"''
      ''bind -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"''
      ''bind -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"''
      ''bind -n C-\\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"''
    ]
    ++ [ "" ]
    ++ [ "# ── Window / pane keybinds ──" ]
    ++ [ "bind f resize-pane -Z" ]
    ++ [ ''bind-key v split-window -h -c "#{pane_current_path}"'' ]
    ++ [ ''bind-key s split-window -v -c "#{pane_current_path}"'' ]
    ++ [ "" ]
    ++ [ "# ── Pane resize ──" ]
    ++ [ "bind -r Left resize-pane -L 5" ]
    ++ [ "bind -r Down resize-pane -D 5" ]
    ++ [ "bind -r Up resize-pane -U 5" ]
    ++ [ "bind -r Right resize-pane -R 5" ]
    ++ [ "bind-key -r M-h resize-pane -L 2" ]
    ++ [ "bind-key -r M-j resize-pane -D 2" ]
    ++ [ "bind-key -r M-k resize-pane -U 2" ]
    ++ [ "bind-key -r M-l resize-pane -R 2" ]
    ++ [ "" ]
    ++ [ "# ── Pane swapping ──" ]
    ++ [ "bind-key j swap-pane -D" ]
    ++ [ "bind-key k swap-pane -U" ]
    ++ [ "" ]
    ++ [ "# ── Reload ──" ]
    ++ [ ''bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"'' ]
    ++ [ "" ]
    ++ [ "# ── Window control ──" ]
    ++ [ ''bind w new-window -c "#{pane_current_path}"'' ]
    ++ [ "bind q kill-pane" ]
    ++ [ "" ]
    ++ optionals cfg.enableSesh [
      "# ── Sesh session manager ──"
      ''bind -N "last-session (via sesh) " Tab run-shell "sesh last"''
      "bind-key \"${cfg.seshBind}\" run-shell \"${seshCmd}\""
    ]
    ++ [ "" ]
    ++ [ "# ── Options ──" ]
    ++ [ "set -s focus-events ${if cfg.focusEvents then "on" else "off"}" ]
    ++ [ ''set -g default-terminal "${cfg.defaultTerminal}"'' ]
    ++ [ "set -as terminal-overrides '${cfg.terminalOverrides}'" ]
    ++ [ "set -g base-index ${toString cfg.baseIndex}" ]
    ++ [ "set -g pane-base-index ${toString cfg.paneBaseIndex}" ]
    ++ [ "set-window-option -g pane-base-index ${toString cfg.paneBaseIndex}" ]
    ++ [ "set-option -g renumber-windows ${if cfg.renumberWindows then "on" else "off"}" ]
    ++ [ "set -g mouse ${if cfg.mouse then "on" else "off"}" ]
    ++ [ "set -g status ${if cfg.status then "on" else "off"}" ]
    ++ [ "set-option -g status-position ${cfg.statusPosition}" ]
    ++ [ "setw -g mode-keys ${cfg.modeKeys}" ]
    ++ [ "set -g detach-on-destroy ${if cfg.detachOnDestroy then "on" else "off"}" ]
    ++ [ "set -g escape-time ${toString cfg.escapeTime}" ]
    ++ [ "set -g history-limit ${toString cfg.historyLimit}" ]
    ++ [ "set -g set-clipboard ${cfg.setClipboard}" ]
    ++ [ "" ]
    ++ optionals (enabledPlugins != {}) [
      "# ── Plugin settings ──"
    ]
    ++ [ (concatStringsSep "\n" (mapAttrsToList (name: pcfg:
      let
        settingsLines = mkPluginSettings name pcfg;
        fzfEnvLines = mkFzfEnv name pcfg;
        yankBindings = ''
          bind-key -T copy-mode-vi v send-keys -X begin-seleciton
          bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
          bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
        '';
      in
        concatStringsSep "\n" (
          (optional (settingsLines != "") "# ${name} settings")
          ++ (optional (settingsLines != "") settingsLines)
          ++ (optional (fzfEnvLines != "") fzfEnvLines)
          ++ (optional (name == "yank") yankBindings)
        )
    ) enabledPlugins)) ]
    ++ [ "" ]
    ++ [ "# ── Plugins ──" ]
    ++ mapAttrsToList (name: pcfg: mkPluginLine name) enabledPlugins
    ++ [ "" ]
    ++ optionals (!isServer) [
      "# ── Theme ──"
      "source-file ~/.config/tmux/theme.conf"
    ]
    ++ [ "" ]
    ++ optionals (cfg.plugins.tpm.enable or false) [
      "# Initialize TPM"
      "run '~/.config/tmux/plugins/tpm/tpm'"
    ]
    ++ [ "" ]
    ++ [ "set -g allow-passthrough ${if cfg.allowPassthrough then "on" else "off"}" ]
    ++ optionals (cfg.extraConfig != "") [ "" cfg.extraConfig ]
    ;

  # ── Build reset.conf ────────────────────────────────────────────

  resetConfLines = map (key: "unbind ${key}") cfg.resetBinds
    ++ optional (cfg.extraResetConfig != "") cfg.extraResetConfig;

in {
  options.programs.nix-tmux = {
    enable = lib.mkEnableOption "nix-managed tmux configuration" // { default = true; };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.tmux;
      description = "tmux package to use";
    };

    # ── Terminal ──────────────────────────────────────────────

    defaultTerminal = lib.mkOption {
      type = lib.types.str;
      default = "tmux-256color";
      description = "Default terminal type for tmux";
    };

    terminalOverrides = lib.mkOption {
      type = lib.types.str;
      default = ",tmux-256color:RGB";
      description = "Terminal overrides for tmux";
    };

    # ── Indexing ──────────────────────────────────────────────

    baseIndex = lib.mkOption {
      type = lib.types.int;
      default = 1;
      description = "Base index for window numbers";
    };

    paneBaseIndex = lib.mkOption {
      type = lib.types.int;
      default = 1;
      description = "Base index for pane numbers";
    };

    renumberWindows = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Renumber windows when one is removed";
    };

    # ── Display ───────────────────────────────────────────────

    mouse = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable mouse support";
    };

    status = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable status bar";
    };

    statusPosition = lib.mkOption {
      type = lib.types.enum [ "top" "bottom" ];
      default = "bottom";
      description = "Status bar position";
    };

    modeKeys = lib.mkOption {
      type = lib.types.enum [ "vi" "emacs" ];
      default = "vi";
      description = "Mode key style";
    };

    focusEvents = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable focus events";
    };

    # ── Behavior ──────────────────────────────────────────────

    prefix = lib.mkOption {
      type = lib.types.str;
      default = "C-Space";
      description = "Prefix key";
    };

    detachOnDestroy = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Don't exit tmux when closing a session";
    };

    escapeTime = lib.mkOption {
      type = lib.types.int;
      default = 0;
      description = "Escape time delay in ms";
    };

    historyLimit = lib.mkOption {
      type = lib.types.int;
      default = 1000000;
      description = "Scrollback history limit";
    };

    setClipboard = lib.mkOption {
      type = lib.types.enum [ "on" "off" "external" ];
      default = "on";
      description = "System clipboard integration";
    };

    allowPassthrough = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Allow passthrough escape sequences";
    };

    # ── Reset ─────────────────────────────────────────────────

    resetBinds = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "C-b" "f" "z" "c" "w" "q" "x" "s" "C-f" ];
      description = "Keys to unbind in reset config";
    };

    extraResetConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra lines appended to tmux.reset.conf";
    };

    # ── Vim navigator ─────────────────────────────────────────

    enableVimNavigator = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable vim-tmux-navigator style pane switching";
    };

    isVimCommand = lib.mkOption {
      type = lib.types.str;
      default = ''ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'';
      description = "Command to detect vim panes";
    };

    # ── Sesh ──────────────────────────────────────────────────

    enableSesh = lib.mkOption {
      type = lib.types.bool;
      default = !isServer;
      description = "Enable sesh session manager integration";
    };

    seshBind = lib.mkOption {
      type = lib.types.str;
      default = "o";
      description = "Key binding for sesh session picker";
    };

    # ── Status script ─────────────────────────────────────────

    enableStatusScript = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Install tmux-status system info script to ~/.local/bin";
    };

    # ── Plugins ───────────────────────────────────────────────

    plugins = {

      tpm = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Enable TPM (Tmux Plugin Manager)";
        };

        tpmPluginRef = lib.mkOption {
          type = lib.types.str;
          default = "tmux-plugins/tpm";
          description = "TPM plugin reference for @plugin directive";
        };
      };

      sensible = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Enable tmux-sensible (sensible defaults)";
        };

        tpmPluginRef = lib.mkOption {
          type = lib.types.str;
          default = "tmux-plugins/tmux-sensible";
          description = "Plugin reference for @plugin directive";
        };
      };

      yank = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Enable tmux-yank (system clipboard)";
        };

        tpmPluginRef = lib.mkOption {
          type = lib.types.str;
          default = "tmux-plugins/tmux-yank";
          description = "Plugin reference for @plugin directive";
        };
      };

      resurrect = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Enable tmux-resurrect (session persistence)";
        };

        tpmPluginRef = lib.mkOption {
          type = lib.types.str;
          default = "tmux-plugins/tmux-resurrect";
          description = "Plugin reference for @plugin directive";
        };

        settings = lib.mkOption {
          type = lib.types.attrsOf lib.types.str;
          default = {
            continuum-restore = "on";
            resurrect-strategy-nvim = "session";
          };
          description = "Resurrect plugin settings";
        };
      };

      thumbs = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Enable tmux-thumbs (quick copy mode)";
        };

        tpmPluginRef = lib.mkOption {
          type = lib.types.str;
          default = "fcsonline/tmux-thumbs";
          description = "Plugin reference for @plugin directive";
        };
      };

      fzf = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Enable tmux-fzf (fuzzy finder integration)";
        };

        tpmPluginRef = lib.mkOption {
          type = lib.types.str;
          default = "sainnhe/tmux-fzf";
          description = "Plugin reference for @plugin directive";
        };

        env = lib.mkOption {
          type = lib.types.attrsOf lib.types.str;
          default = {
            TMUX_FZF_ORDER = "window|session|command|keybinding";
            TMUX_FZF_SESSION_FORMAT = "#{session_windows} windows";
          };
          description = "Environment variables for tmux-fzf";
        };
      };

      fzf-url = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = !isServer;
          description = "Enable tmux-fzf-url (fzf URL opener)";
        };

        tpmPluginRef = lib.mkOption {
          type = lib.types.str;
          default = "wfxr/tmux-fzf-url";
          description = "Plugin reference for @plugin directive";
        };

        settings = lib.mkOption {
          type = lib.types.attrsOf lib.types.str;
          default = {
            "fzf-url-bind" = "x";
            "fzf-url-open" = "zen";
            "fzf-url-history-limit" = "2000";
          };
          description = "fzf-url plugin settings";
        };
      };

      sessionx = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = osConfig.workstation.home.tmux.sessionx.enable or true;
          description = "Enable tmux-sessionx (fuzzy session manager)";
        };

        tpmPluginRef = lib.mkOption {
          type = lib.types.str;
          default = "omerxx/tmux-sessionx";
          description = "Plugin reference for @plugin directive";
        };
      };
    };

    # ── Extra ─────────────────────────────────────────────────

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra lines appended to tmux.conf";
    };

    themeSource = lib.mkOption {
      type = lib.types.path;
      default = ../config/tmux/theme.conf;
      description = "Path to theme.conf for activation script copy";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ cfg.package ]
      ++ optional cfg.enableStatusScript (
        pkgs.writeShellScriptBin "tmux-status" (readFile ../config/tmux/.local/bin/tmux-status)
      );

    # ── Config files ──────────────────────────────────────────

    xdg.configFile."tmux/tmux.conf".text = concatStringsSep "\n" tmuxConfLines;

    xdg.configFile."tmux/tmux.reset.conf".text =
      concatStringsSep "\n" resetConfLines;

    # ── Activation: copy theme if absent ──────────────────────

    home.activation.ensureTmuxTheme = lib.mkIf (!isServer) (lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      if [ ! -f "$HOME/.config/tmux/theme.conf" ]; then
        install -Dm644 ${cfg.themeSource} "$HOME/.config/tmux/theme.conf"
      fi
    '');

    # ── Activation: symlink enabled plugins ──────────────────

    home.activation.ensureTmuxPlugins = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      ${concatStringsSep "\n" (mapAttrsToList (name: pcfg:
        let
          storePath = pluginStorePaths.${name};
          tpmDir = tpmDirFromRef pcfg.tpmPluginRef;
        in
        ''
          mkdir -p "$HOME/.config/tmux/plugins"
          ln -sfT "${storePath}" "$HOME/.config/tmux/plugins/${tpmDir}"
        ''
      ) enabledPlugins)}
    '';
  };
}
